#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import glob
import os
import pickle

import numpy as np

from sklearn.feature_extraction.text import HashingVectorizer, TfidfTransformer

from aidistillery.file_handling import identifier_from_path
from aidistillery.data_cleaning import normalize_text


def main(args):
    """
    Arguments
    ---------
    :args: Namespace object


    """
    raw_documents = glob.glob(os.path.join(args.datadir, '*'))

    vect = HashingVectorizer(input='filename', stop_words='english', norm=None)
    tfidf = TfidfTransformer(norm='l2')

    X = vect.fit_transform(raw_documents)

    X = tfidf.fit_transform(X)
    ids = [identifier_from_path(d) for d in raw_documents]

    os.makedirs(args.outpath, exist_ok=True)
    with open(os.path.join(args.outpath, "vectorizer.pkl"), 'wb') as fhandle:
        pickle.dump(vect, fhandle)

    with open(os.path.join(args.outpath, "tfidf_sparse.pkl"), 'wb') as fhandle:
        pickle.dump(X, fhandle)

    with open(os.path.join(args.outpath, "index2identifier.pkl"), 'wb') as fhandle:
        pickle.dump(ids, fhandle)







def _add_args(parser):
    parser.add_argument("-d", "--datadir", required=True,
                        help="Path to txt file root")
    parser.add_argument("-o", "--outpath", required=True,
                        help="Path to output directory")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    _add_args(parser)
    args = parser.parse_args()
    main(args)
